repos:
  - repo: https://github.com/domluna/JuliaFormatter.jl
    rev: v1.0.22
    hooks:
      - id: julia-formatter
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.6.0
    hooks:
      - id: markdownlint-cli2-fix
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.7.1
          - prettier-plugin-sh@0.11.0
          - prettier-plugin-toml@0.3.1
